# Generated by Django 5.1.2 on 2024-11-27 19:19

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parks',
            fields=[
                ('id', models.IntegerField()),
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('capacity', models.IntegerField(default=0)),
                ('booked', models.IntegerField(default=0)),
                ('available_spaces', models.IntegerField(default=0)),
                ('mpoly', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Parks',
            },
        ),
        migrations.CreateModel(
            name='ParkingSlots',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('slot_no', models.IntegerField()),
                ('is_parked', models.BooleanField(default=False)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.parks')),
            ],
            options={
                'verbose_name_plural': 'Parking Slots',
            },
        ),
    ]
