# Generated by Django 5.1.2 on 2025-01-09 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionnairedata',
            options={'verbose_name_plural': 'Questionnaire Data'},
        ),
        migrations.RenameField(
            model_name='questionnairedata',
            old_name='formStatus',
            new_name='form_status',
        ),
        migrations.RenameField(
            model_name='questionnairedata',
            old_name='formTitle',
            new_name='form_title',
        ),
    ]
